.TH EXAMPLE 1 "2022-02-05" "example" "A test application for mango-kong."
.SH NAME
example - A test application for mango-kong\&.
.SH SYNOPSIS
\fBexample\fP [\fIoptions\&.\&.\&.\fP] [\fIargument\&.\&.\&.\fP]
.SH DESCRIPTION
And this is more detail about what this does\&.
.SH OPTIONS
.TP
\fB--dest=DIR\fP
Destination directory\&.
.TP
\fB-h, --help\fP
Show context-sensitive help\&.
.TP
\fB--log="debug"\fP
Log level (debug,info,warn,error)\&.
.TP
\fB--man\fP
Print man page\&.
.SH COMMANDS
.TP
\fBdelete <command>\fP
.RS 4
Delete command\&.
.RE
.TP
\fBCOMMANDS\fP
.RS 4
\fBdelete user <user> \&.\&.\&.\fP
.RS 4
Delete users\&.
.RE
.TP
\fBOPTIONS\fP
.RS 4
\fB--purge\fP
Completely purge all history for the user\&.
.RE
.RE
.TP
\fBinfo <command>\fP
.RS 4
Info command\&.
.RE
.TP
\fBCOMMANDS\fP
.RS 4
\fBinfo system\fP
.RS 4
Info on the system\&.
.RE
.TP
\fBinfo user <user> \&.\&.\&.\fP
.RS 4
Info on users\&.
.RE
.RE
